server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/secondhand?useSSL=false&serverTimezone=UT&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  redis:
    # host: 192.168.239.137
    host: 127.0.0.1
    port: 6379
#    password: ???
    lettuce:
      pool:
        # 核心改动：将最大并发连接拉满至与 Tomcat 并发处理能力匹配
        max-active: 200
        # 最大空闲连接也要放开，防止高并发刚结束时瞬间销毁大量连接引发抖动
        max-idle: 200
        # 最小保活连接，平时哪怕没流量也与 Redis 维持十个长连接保持热身
        min-idle: 10
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug